server:
  port: 7000
  servlet:
    context-path: /auth
spring:
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        group: DEFAULT
  application:
    name: wong-auth
mall:
  auth:
    clientId: admin-app
    clientSecret: 123456
    grantType: password
    ignore:
      urls:
        - "/doc.html"
        - "/swagger-ui.html"
        - "/swagger-resources/**"
        - "/swagger/**"
        - "/**/v2/api-docs"
        - "/**/*.js"
        - "/**/*.css"
        - "/**/*.png"
        - "/**/*.ico"
        - "/webjars/**"
logging:
  level:
    org.springframework.security: debug
encrypt:
  key-store:
    location: classpath:jwt.jks
    secret: 123456
    alias: jwt.jks
    password: 123456
    type: jks